### PR TITLE
322 navigation tile

### PR DESCRIPTION
**Pull request by simonedeponti**
Adds the navigation tile (very prototypal, needs further development already scheduled)

### CODE REVIEW

**Comment by simonedeponti** [comment]
Jenkin's green: http://jenkins.ploneintranet.net/job/Plone%20Intranet%20workspace/28/

**Comment by adamcheasley** [comment]
It's a little confusing to have both travis *and* jenkins running tests. Especially when one is passing and the other is failing. Can we not go with one or the other?

**Comment by do3cc** [comment]
Yes, but I don't know what to do with the travis tests

**Comment by mattss** [comment]
We set up travis integration when this was one of the only ploneintranet packages around, as it was the simplest way to make the tests visible to all. The move to a centralised jenkins makes sense - and IMO travis should now be ditched.

**Comment by mattss** [comment]
It should also be possible to integrate jenkins with github so that jenkins updates the status of pull requests automatically in the same way that travis currently does.

**Comment by do3cc** [comment]
I added and configured this pull request thing today for every package

**Pull request merged**
