### PR TITLE
Workspace status adapter

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by ale-rt** [comment]
@cornae, @gyst , is there a reason why we should have different ids (new-post-box and post-box) for an element that has the same functionality?
 - https://github.com/ploneintranet/ploneintranet.workspace/commit/551f0d66c6b1bb09c3acf2ad4b3b4f439c51776a

the form in the [home page](http://demo.ploneintranet.net/dashboard.html?) has the id new-post-box, and the one in the [workspace](http://demo.ploneintranet.net/open-market-committee/) has the id post-box.

Fact is that the functionality is strongly dependent on the ids becuase the pattern uses the id for selecting html element.

**Comment by cornae** [comment]
No they may have the same ID since they are on different pages. It doesn’t matter.

**Comment by ale-rt** [comment]
On Tue, Feb 3, 2015 at 4:30 PM, Cornelis G. A. Kolbach <
notifications@github.com> wrote:

> No they may have the same ID since they are on different pages. It doesn’t
> matter.


This for sure, but I was wondering if it would be better:
 1. to unify the markup
 2. modify the pat-inject in such a way that no ids are used as selectors

This would allow, for example, the possibility to include the same element
twice on a page.

Just some free thougths :)
-- 
Alessandro Pisa - RedTurtle Technology
E-mail: alessandro.pisa@redturtle.it
Web Site: http://www.redturtle.it
Phone: +39 0532 1915958

**Comment by cornae** [comment]
> Op 3 feb. 2015, om 16:37 heeft Alessandro Pisa <notifications@github.com> het volgende geschreven:
> 
> > No they may have the same ID since they are on different pages. It doesn’t 
> > matter. 
> 
> 
> This for sure, but I was wondering if it would be better: 
> 1. to unify the markup 
> 2. modify the pat-inject in such a way that no ids are used as selectors 
> 
> This would allow, for example, the possibility to include the same element 
> twice on a page. 
> 
> Just some free thougths :) 

That’s already the case. Every instance of update-social gets its own idea in the liquid include. That’s why we can have multiple on one page.

{% include update-social.html id="post-box”  … =

**Comment by ale-rt** [comment]
On Tue, Feb 3, 2015 at 4:40 PM, Cornelis G. A. Kolbach <
notifications@github.com> wrote:

>
> > Op 3 feb. 2015, om 16:37 heeft Alessandro Pisa <notifications@github.com>
> het volgende geschreven:
> >
> > > No they may have the same ID since they are on different pages. It
> doesn’t
> > > matter.
> >
> >
> > This for sure, but I was wondering if it would be better:
> > 1. to unify the markup
> > 2. modify the pat-inject in such a way that no ids are used as selectors
> >
> > This would allow, for example, the possibility to include the same
> element
> > twice on a page.
> >
> > Just some free thougths :)
>
> That’s already the case. Every instance of update-social gets its own idea
> in the liquid include. That’s why we can have multiple on one page.
>
> {% include update-social.html id="post-box” … =
>
> Now I see :)
You are referring to this file:
https://github.com/ploneintranet/ploneintranet.theme/blob/b7ef87b598b5eb6d64b68eafd3cda90220ddff3a/prototype/_includes/update-social.html
aren't you?

Thanks for clarifying :)
Ciao!
-- 
Alessandro Pisa - RedTurtle Technology
E-mail: alessandro.pisa@redturtle.it
Web Site: http://www.redturtle.it
Phone: +39 0532 1915958

**Comment by cornae** [comment]
> Op 3 feb. 2015, om 16:45 heeft Alessandro Pisa <notifications@github.com> het volgende geschreven:
> 
> Now I see :) 
> You are referring to this file: 
> https://github.com/ploneintranet/ploneintranet.theme/blob/b7ef87b598b5eb6d64b68eafd3cda90220ddff3a/prototype/_includes/update-social.html 
> aren't you? 
> 
> Thanks for clarifying :) 
> Ciao! 

Yes, that’s the only include for update social that’s used for every instance of it. In it every reference to the id of the instance that is used for pat-switch, pat-toggle or pat-inject is prefixed with the same ID to guarantee that multiple instances can work next to each other on the same page.=

**Comment by pilz** [comment]
Looks sane and works for me. merging

**Pull request merged**
