### PR TITLE
Feature/workspace tiled mock

### PR DESCRIPTION
**Pull request by pilz**
This integrates the workspace view, a workspaces view, a workspace add form and a sidebar with mock tiles in the workspace.

IMPORTANT: Must be merged at the same time as the pull request with the same name on ploneintranet.theme

### CODE REVIEW

**Comment by adamcheasley** [comment]
I'm not sure of the difference between this pull request and the previous one, but my comments from https://github.com/ploneintranet/ploneintranet.workspace/pull/41 still stand.

**Comment by mattss** [comment]
Are we still allowing code review on pull requests before merging them? I agree with @adamcheasley's points from #41, which should be fairly simple to fix.

**Comment by pilz** [comment]
Of course we allow them :) This is just a case of overlapping, I think. And your comments go to me, not the reviewer, who doesn't see them necessarily right away. 

I'll fix the quoting now. The outcommenting has just been agreed in irc with different people and is a transitional thing while we are refactoring this. We need them to stay very visible for now. Therefore outcommented. Once moved - and rewritten for the new theme - they'll vanish there.

**Comment by mattss** [comment]
Ok great thanks for the explanation @pilz

**Pull request merged**
